# Generated by Django 5.1.4 on 2025-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='Raju Electricals and Hardwares', max_length=150),
        ),
    ]
