# Generated by Django 5.1.4 on 2025-01-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_manual',
            field=models.FileField(blank=True, help_text='Upload a PDF manual', null=True, upload_to='product_pdfs/'),
        ),
    ]
