# Generated by Django 5.1.4 on 2025-01-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_product_pdf_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='a_tag',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
